//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D2Boomer_AppSettings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Diablo II\\")]
        public string Diablo2_Path {
            get {
                return ((string)(this["Diablo2_Path"]));
            }
            set {
                this["Diablo2_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string D2B_OutputPath {
            get {
                return ((string)(this["D2B_OutputPath"]));
            }
            set {
                this["D2B_OutputPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Sets</string>
  <string>UniqueItems</string>
  <string>SetItems</string>
  <string>Armor</string>
  <string>Gems</string>
  <string>Weapons</string>
  <string>Misc</string>
  <string>Skills</string>
  <string>MonStats</string>
  <string>Runes</string>
  <string>ItemStatCost</string>
  <string>MagicPrefix</string>
  <string>Properties</string>
  <string>MagicSuffix</string>
  <string>ItemTypes</string>
  <string>CharStats</string>
  <string>NPC</string>
  <string>CubeMain</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RequiredTxtFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RequiredTxtFiles"]));
            }
        }
    }
}
